import { NextResponse } from "next/server";
import JSZip from "jszip";
import { prisma } from "@/lib/db";
import { requirePermission } from "@/lib/auth";
import { toCsv } from "@/lib/csv";
import { recordAudit } from "@/lib/audit";

/**
 * Inspection evidence pack export (PRD Module 18, ICMS-078/080).
 * Route handler — runs outside the app layout; auth is enforced inline.
 */
export async function GET() {
  const user = await requirePermission("inspection.run");

  const [licence, workers, cosRecords] = await Promise.all([
    prisma.sponsorLicence.findFirst({ include: { organisation: true } }),
    prisma.worker.findMany({ include: { appendixD: true }, orderBy: { wcid: "asc" } }),
    prisma.cos.findMany({ orderBy: { createdAt: "desc" } }),
  ]);

  const generatedAt = new Date().toISOString();
  const zip = new JSZip();

  // 00 — cover
  zip.file(
    "00_cover.txt",
    [
      "ELMS Health Solutions Ltd",
      "============================================",
      "UKVI Inspection Evidence Pack",
      "============================================",
      "",
      `Generated at: ${generatedAt}`,
      `Generated by: ${user.displayName}`,
    ].join("\n"),
  );

  // 01 — index
  zip.file(
    "01_index.txt",
    [
      "Contents of this inspection evidence pack:",
      "",
      "00_cover.txt              — Cover sheet and generation metadata",
      "01_index.txt              — This index",
      "02_sponsor_licence.json   — Sponsor licence and organisation record",
      "03_worker_register.csv    — Full sponsored worker register",
      "04_cos_register.csv       — Certificate of Sponsorship register",
      "workers/<WCID>_appendixD.txt — Per-worker Appendix D evidence checklist",
    ].join("\n"),
  );

  // 02 — sponsor licence + organisation
  zip.file("02_sponsor_licence.json", JSON.stringify(licence, null, 2));

  // 03 — worker register
  const workerRows = workers.map((w) => ({
    wcid: w.wcid,
    legalName: w.legalName,
    jobTitle: w.jobTitle ?? "",
    socCode: w.socCode ?? "",
    workLocation: w.workLocation ?? "",
    sponsorshipStatus: w.sponsorshipStatus,
    complianceScore: w.complianceScore,
    ragStatus: w.ragStatus,
  }));
  zip.file("03_worker_register.csv", toCsv(workerRows));

  // 04 — CoS register
  const cosRows = cosRecords.map((c) => ({
    cosNumber: c.cosNumber ?? "",
    candidateName: c.candidateName ?? "",
    jobTitle: c.jobTitle,
    socCode: c.socCode,
    salary: c.salary,
    status: c.status,
  }));
  zip.file("04_cos_register.csv", toCsv(cosRows));

  // workers/<wcid>_appendixD.txt
  for (const w of workers) {
    const lines = [
      `Appendix D evidence — ${w.legalName} (${w.wcid})`,
      "--------------------------------------------------",
      "",
      ...(w.appendixD.length === 0
        ? ["No Appendix D items recorded."]
        : w.appendixD.map(
            (i) => `${i.label}: ${i.status}${i.required ? " (required)" : ""}`,
          )),
    ];
    zip.file(`workers/${w.wcid}_appendixD.txt`, lines.join("\n"));
  }

  const buf = await zip.generateAsync({ type: "uint8array" });

  await recordAudit({
    actor: user,
    action: "inspection.export",
    entityType: "InspectionPack",
    summary: "Inspection pack generated",
  });

  // Cast: runtime (Response/NextResponse) accepts a Uint8Array body; the cast
  // only sidesteps the TS lib's over-narrow BodyInit typing for typed arrays.
  return new NextResponse(buf as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": 'attachment; filename="ICMS-Inspection-Pack.zip"',
    },
  });
}
