import { getCurrentUser } from "@/lib/auth";
import { fmtDate } from "@/lib/dates";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { pageGuard } from "@/components/forbidden";
import { getReportRows, reportTitle } from "../../reports";

export const dynamic = "force-dynamic";

// Printable, ELMS-branded report view (PRD Module 31, ICMS-107).
export default async function ReportViewPage({ params }: { params: { type: string } }) {
  const guard = await pageGuard("reports.view");
  if (guard) return guard;

  const rows = await getReportRows(params.type);
  if (rows === null) {
    return <p className="text-muted-foreground">Unknown report.</p>;
  }

  const [user] = await Promise.all([getCurrentUser()]);
  const columns = rows.length > 0 ? Object.keys(rows[0]) : [];

  return (
    <div className="space-y-5 bg-white p-2 print:p-0">
      {/* ELMS-branded letterhead */}
      <div className="flex items-start justify-between gap-4 border-b-2 border-elms-navy pb-4">
        <div>
          <div className="text-lg font-bold text-elms-navy">ELMS Health Solutions Ltd</div>
          <h2 className="mt-1 text-xl font-semibold text-elms-navy">{reportTitle(params.type)}</h2>
          <div className="mt-1 text-xs text-muted-foreground">
            Generated {fmtDate(new Date())} · Generated by {user?.displayName ?? "—"}
          </div>
        </div>
        <p className="max-w-[14rem] text-right text-xs text-muted-foreground print:hidden">
          Use your browser&rsquo;s Print command to save this report as a PDF.
        </p>
      </div>

      {rows.length === 0 ? (
        <p className="text-sm text-muted-foreground">No data for this report.</p>
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              {columns.map((c) => (
                <TableHead key={c}>{c}</TableHead>
              ))}
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row, i) => (
              <TableRow key={i}>
                {columns.map((c) => (
                  <TableCell key={c}>{row[c] === null || row[c] === undefined ? "" : String(row[c])}</TableCell>
                ))}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
    </div>
  );
}
