"""baseline

Revision ID: 5a7ed2d087f3
Revises: 
Create Date: 2026-04-16 20:16:47.772262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a7ed2d087f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('FUND', 'SUB_FUND', 'SPV', 'BLOCKER', 'FEEDER', 'CO_INVEST', 'MASTER', 'AIV', name='entitytype'), nullable=False),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=128), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('reporting_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'ACTIVE', 'WINDING_DOWN', 'CLOSED', 'INACTIVE', name='entitystatus'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='interfacedirection'), nullable=False),
    sa.Column('source_owner', sa.String(length=128), nullable=False),
    sa.Column('target_owner', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('mapping_json', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('retry_policy', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=False),
    sa.Column('domicile', sa.String(length=64), nullable=False),
    sa.Column('tax_classification', sa.String(length=64), nullable=True),
    sa.Column('regulatory_classification', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PROSPECT', 'ACTIVE', 'REDEEMED', 'TRANSFERRED', 'INACTIVE', name='investorstatus'), nullable=False),
    sa.Column('side_letter', sa.Boolean(), nullable=False),
    sa.Column('special_economics_json', sa.String(), nullable=True),
    sa.Column('primary_contact', sa.String(length=255), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lineage_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upstream_type', sa.String(length=64), nullable=False),
    sa.Column('upstream_id', sa.String(length=64), nullable=False),
    sa.Column('downstream_type', sa.String(length=64), nullable=False),
    sa.Column('downstream_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('roles_json', sa.String(), nullable=False),
    sa.Column('fund_scope_json', sa.String(), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='periodtype'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SOFT_CLOSE', 'CLOSED', 'REOPENED', 'ARCHIVED', name='periodstatus'), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reopen_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'period_type', 'period_start', name='uq_period')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_system', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.String(), nullable=True),
    sa.Column('after_state', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_class', sa.String(length=32), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.Column('contributed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('distributed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('recallable', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ending_nav', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('allocated_pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('rights_json', sa.String(), nullable=True),
    sa.Column('carry_participant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('investor_id', 'entity_id', 'investor_class', name='uq_capital_account')
    )
    op.create_table('capital_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(length=32), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.Enum('INVESTMENT', 'MANAGEMENT_FEE', 'EXPENSE', 'RETURN_OF_CAPITAL', 'PROFIT', 'RECALLABLE_RETURN', name='casheventpurpose'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'call_number', name='uq_call_number')
    )
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('closing_id', sa.String(length=32), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('investor_class', sa.String(length=32), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=True),
    sa.Column('commitment_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investor_id', 'entity_id', 'closing_id', name='uq_commitment_closing')
    )
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('distribution_number', sa.String(length=32), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.Enum('INVESTMENT', 'MANAGEMENT_FEE', 'EXPENSE', 'RETURN_OF_CAPITAL', 'PROFIT', 'RECALLABLE_RETURN', name='casheventpurpose'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('recallable', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'distribution_number', name='uq_distribution_number')
    )
    op.create_table('entity_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.String(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'effective_from', name='uq_entity_version_from')
    )
    op.create_table('fee_calculation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('schedule_version_snapshot', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_class', sa.String(length=32), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('basis', sa.Enum('COMMITMENT', 'INVESTED_CAPITAL', 'NAV', 'FLAT', name='feebasis'), nullable=False),
    sa.Column('annual_rate_bps', sa.Integer(), nullable=False),
    sa.Column('periodicity', sa.String(length=16), nullable=False),
    sa.Column('step_down_json', sa.String(), nullable=True),
    sa.Column('offsets_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_owner', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mapping_version', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.String(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interface_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('reconciliation_ok', sa.Boolean(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_source', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('reconciliation_type', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('source_total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_total', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'MATCHED', 'BREAK', 'SIGNED_OFF', name='reconciliationstatus'), nullable=False),
    sa.Column('signed_off_by_user_id', sa.Integer(), nullable=True),
    sa.Column('remediation_note', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['signed_off_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waterfall_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_class', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('method', sa.Enum('AMERICAN', 'EUROPEAN', 'HYBRID', name='waterfallmethod'), nullable=False),
    sa.Column('preferred_return_bps', sa.Integer(), nullable=False),
    sa.Column('catchup_percentage_bps', sa.Integer(), nullable=False),
    sa.Column('carried_interest_bps', sa.Integer(), nullable=False),
    sa.Column('gp_catchup_share_bps', sa.Integer(), nullable=False),
    sa.Column('hurdle_compounding', sa.String(length=32), nullable=False),
    sa.Column('tiers_json', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_call_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('capital_account_id', sa.Integer(), nullable=False),
    sa.Column('commitment_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pro_rata_share', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['capital_calls.id'], ),
    sa.ForeignKeyConstraint(['capital_account_id'], ['capital_accounts.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('close_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('depends_on_step_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signed_off_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['close_steps.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['signed_off_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('capital_account_id', sa.Integer(), nullable=False),
    sa.Column('allocation_basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pro_rata_share', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['capital_account_id'], ['capital_accounts.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_accruals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('basis_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('applied_rate_bps', sa.Integer(), nullable=False),
    sa.Column('gross_fee', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('offset_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_fee', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['fee_calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['fee_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('source_payload', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('remediation_note', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nav_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('capital_account_id', sa.Integer(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('gross_asset_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liabilities', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ending_nav', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_reference', sa.String(length=128), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capital_account_id'], ['capital_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'investor_id', 'as_of', name='uq_nav_snapshot')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_reference', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('capital_account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('CAPITAL_CALL', 'CONTRIBUTION', 'DISTRIBUTION', 'RECALL', 'MGMT_FEE', 'FEE_OFFSET', 'EXPENSE', 'NAV', 'REALISED_GAIN', 'REALISED_LOSS', 'UNREALISED_PNL', 'PORTFOLIO_CASH_IN', 'PORTFOLIO_CASH_OUT', 'JOURNAL', name='transactiontype'), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'VALIDATED', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REVERSED', 'REJECTED', name='transactionstate'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reversed_by_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['capital_account_id'], ['capital_accounts.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'source_reference', name='uq_tx_source_ref')
    )
    op.create_table('waterfall_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('scenario_label', sa.String(length=128), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('executed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version_snapshot', sa.String(), nullable=False),
    sa.Column('is_scenario', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'POSTED', 'REJECTED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['waterfall_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('source_transaction_id', sa.Integer(), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reversed_by_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('participant', sa.String(length=128), nullable=False),
    sa.Column('participant_type', sa.String(length=32), nullable=False),
    sa.Column('allocation_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['waterfall_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waterfall_tier_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(length=64), nullable=False),
    sa.Column('lp_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('gp_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('formula_text', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['waterfall_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('capital_account_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.id'], ),
    sa.ForeignKeyConstraint(['capital_account_id'], ['capital_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_lines')
    op.drop_table('waterfall_tier_results')
    op.drop_table('participant_allocations')
    op.drop_table('journal_entries')
    op.drop_table('waterfall_runs')
    op.drop_table('transactions')
    op.drop_table('nav_snapshots')
    op.drop_table('import_exceptions')
    op.drop_table('fee_accruals')
    op.drop_table('distribution_allocations')
    op.drop_table('close_steps')
    op.drop_table('capital_call_allocations')
    op.drop_table('waterfall_models')
    op.drop_table('reconciliations')
    op.drop_table('jobs')
    op.drop_table('interface_runs')
    op.drop_table('import_batches')
    op.drop_table('fee_schedules')
    op.drop_table('fee_calculation_runs')
    op.drop_table('entity_versions')
    op.drop_table('distributions')
    op.drop_table('commitments')
    op.drop_table('capital_calls')
    op.drop_table('capital_accounts')
    op.drop_table('audit_events')
    op.drop_table('accounting_periods')
    op.drop_table('users')
    op.drop_table('lineage_edges')
    op.drop_table('investors')
    op.drop_table('interfaces')
    op.drop_table('gl_accounts')
    op.drop_table('entities')
    # ### end Alembic commands ###
